// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChat(arg1) {
  return window['go']['main']['App']['ClearChat'](arg1);
}

export function CreateChat(arg1, arg2) {
  return window['go']['main']['App']['CreateChat'](arg1, arg2);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function Signup(arg1, arg2) {
  return window['go']['main']['App']['Signup'](arg1, arg2);
}

export function UpdateAutoExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['UpdateAutoExecuteQuery'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}

export function UpdateSelectedTables(arg1, arg2) {
  return window['go']['main']['App']['UpdateSelectedTables'](arg1, arg2);
}
