// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearChat(arg1:string):Promise<Record<string, any>>;

export function CreateChat(arg1:main.Connection,arg2:boolean):Promise<Record<string, any>>;

export function DeleteChat(arg1:string):Promise<Record<string, any>>;

export function GetChats():Promise<Record<string, any>>;

export function GetMessages(arg1:string):Promise<Record<string, any>>;

export function GetUser():Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, any>>;

export function SendMessage(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Signup(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UpdateAutoExecuteQuery(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function UpdateConnection(arg1:string,arg2:main.Connection,arg3:boolean):Promise<Record<string, any>>;

export function UpdateSelectedTables(arg1:string,arg2:string):Promise<Record<string, any>>;
